spring:
  datasource:
    url: jdbc:mysql://localhost:13306/weibo-visualization?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456